# -*- coding: utf-8 -*-
"""Matrices RGB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12nofqmQRbgbfROcT2e0FJBJ5x5wJweRZ
"""

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import requests
from io import BytesIO

# 1. Obtener imagen objetivo (120x180 RGB) desde la web
url = "https://picsum.photos/180/120"
response = requests.get(url)
target_img = np.array(Image.open(BytesIO(response.content)).convert('RGB'))

# Configuración del Algoritmo Genético
POP_SIZE = 50
HEIGHT, WIDTH, CHANNELS = 120, 180, 3
GENERATIONS = 50
MUTATION_RATE = 0.01  # Pequeña tasa para perturbar la población

# 2. Generar población inicial aleatoria (50 matrices de 120x180x3)
population = np.random.randint(0, 256, (POP_SIZE, HEIGHT, WIDTH, CHANNELS), dtype=np.uint8)
initial_sample = population[0].copy()

# Lista para guardar la mejor imagen de cada generación
history = []

# Función de aptitud (Error absoluto medio: menor diferencia = mejor aptitud)
def get_fitness(pop):
    return np.mean(np.abs(pop.astype(int) - target_img.astype(int)), axis=(1, 2, 3))

# 3. Proceso evolutivo
for gen in range(GENERATIONS):
    fitness = get_fitness(population)
    idx = np.argsort(fitness)
    population = population[idx]  # Ordenar de mejor a peor

    # Guardar la mejor imagen actual de esta generación
    history.append(population[0].copy())

    # Elitismo: Mantener los 5 mejores individuos
    new_pop = list(population[:5])

    # Reproducción y mutación hasta completar la población
    while len(new_pop) < POP_SIZE:
        # Selección entre los mejores 15 padres
        p1 = population[np.random.randint(0, 15)]
        p2 = population[np.random.randint(0, 15)]

        # Cruce guiado píxel por píxel:
        dist1 = np.abs(p1.astype(int) - target_img.astype(int))
        dist2 = np.abs(p2.astype(int) - target_img.astype(int))

        # Elegimos el píxel del padre que esté más cerca de la imagen objetivo
        child = np.where(dist1 < dist2, p1, p2).astype(np.uint8)

        # Mutación local no guiada (perturbación de valor cercano al actual)
        mut_mask = np.random.rand(HEIGHT, WIDTH, CHANNELS) < MUTATION_RATE
        if np.any(mut_mask):
            # Generamos un cambio aleatorio de entre -10 y +10
            jitter = np.random.randint(-30, 31, size=np.sum(mut_mask))
            mutated_pixels = np.clip(child[mut_mask].astype(int) + jitter, 0, 255).astype(np.uint8)
            child[mut_mask] = mutated_pixels

        new_pop.append(child)

    population = np.array(new_pop)

# 4. Presentación gráfica de todas las generaciones
fig, axes = plt.subplots(1, GENERATIONS + 2, figsize=(3 * (GENERATIONS + 2), 4))

# Mostrar población inicial
axes[0].imshow(initial_sample)
axes[0].set_title("Población Inicial")
axes[0].axis('off')

# Mostrar cada una de las generaciones en su evolución
for i, img in enumerate(history):
    axes[i + 1].imshow(img)
    axes[i + 1].set_title(f"Gen {i + 1}")
    axes[i + 1].axis('off')

# Mostrar imagen objetivo al final
axes[-1].imshow(target_img)
axes[-1].set_title("Objetivo")
axes[-1].axis('off')

plt.tight_layout()
plt.show()